var d={instantiateWasm:function(a,b){var c=performance.now();instantiateCachedURL(wasmCacheVersion,"re2.wasm",a).then(function(a){b(a);console.log(performance.now()-c)});return{}}},aa={},n;for(n in d)d.hasOwnProperty(n)&&(aa[n]=d[n]);var ba=!1,q=!1,ca=!1,da=!1;
if(d.ENVIRONMENT)if("WEB"===d.ENVIRONMENT)ba=!0;else if("WORKER"===d.ENVIRONMENT)q=!0;else if("NODE"===d.ENVIRONMENT)ca=!0;else if("SHELL"===d.ENVIRONMENT)da=!0;else throw Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.");else ba="object"===typeof window,q="function"===typeof importScripts,ca="object"===typeof process&&"function"===typeof require&&!ba&&!q,da=!ba&&!ca&&!q;
if(ca){d.print||(d.print=console.log);d.printErr||(d.printErr=console.warn);var ga,ha;d.read=function(a,b){ga||(ga=require("fs"));ha||(ha=require("path"));a=ha.normalize(a);var c=ga.readFileSync(a);return b?c:c.toString()};d.readBinary=function(a){a=d.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};d.load=function(a){ia(read(a))};d.thisProgram||(d.thisProgram=1<process.argv.length?process.argv[1].replace(/\\/g,"/"):"unknown-program");d.arguments=process.argv.slice(2);"undefined"!==
typeof module&&(module.exports=d);process.on("uncaughtException",function(a){if(!(a instanceof ja))throw a;});d.inspect=function(){return"[Emscripten Module object]"}}else if(da)d.print||(d.print=print),"undefined"!=typeof printErr&&(d.printErr=printErr),d.read="undefined"!=typeof read?read:function(){throw"no read() available";},d.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?
d.arguments=scriptArgs:"undefined"!=typeof arguments&&(d.arguments=arguments),"function"===typeof quit&&(d.quit=function(a){quit(a)}),eval("if (typeof gc === 'function' && gc.toString().indexOf('[native code]') > 0) var gc = undefined");else if(ba||q)d.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},q&&(d.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return b.response}),d.readAsync=function(a,
b,c){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||0==e.status&&e.response?b(e.response):c()};e.onerror=c;e.send(null)},"undefined"!=typeof arguments&&(d.arguments=arguments),"undefined"!==typeof console?(d.print||(d.print=function(a){console.log(a)}),d.printErr||(d.printErr=function(a){console.warn(a)})):d.print||(d.print=function(){}),q&&(d.load=importScripts),"undefined"===typeof d.setWindowTitle&&(d.setWindowTitle=function(a){document.title=
a});else throw"Unknown runtime environment. Where are we?";function ia(a){eval.call(null,a)}!d.load&&d.read&&(d.load=function(a){ia(d.read(a))});d.print||(d.print=function(){});d.printErr||(d.printErr=d.print);d.arguments||(d.arguments=[]);d.thisProgram||(d.thisProgram="./this.program");d.quit||(d.quit=function(a,b){throw b;});d.print=d.print;d.k=d.printErr;d.preRun=[];d.postRun=[];for(n in aa)aa.hasOwnProperty(n)&&(d[n]=aa[n]);
var aa=void 0,v={g:function(a){return tempRet0=a},P:function(){return tempRet0},W:function(){return u},V:function(a){u=a},F:function(a){switch(a){case "i1":case "i8":return 1;case "i16":return 2;case "i32":return 4;case "i64":return 8;case "float":return 4;case "double":return 8;default:return"*"===a[a.length-1]?v.p:"i"===a[0]?(a=parseInt(a.substr(1)),assert(0===a%8),a/8):0}},N:function(a){return Math.max(v.F(a),v.p)},aa:16,xa:function(a,b){"double"===b||"i64"===b?a&7&&(assert(4===(a&7)),a+=4):assert(0===
(a&3));return a},ka:function(a,b,c){return c||"i64"!=a&&"double"!=a?a?Math.min(b||(a?v.N(a):0),v.p):Math.min(b,8):8},q:function(a,b,c){return c&&c.length?d["dynCall_"+a].apply(null,[b].concat(c)):d["dynCall_"+a].call(null,b)},j:[],J:function(a){for(var b=0;b<v.j.length;b++)if(!v.j[b])return v.j[b]=a,2*(1+b);throw"Finished up all reserved function pointers. Use a higher value for RESERVED_FUNCTION_POINTERS.";},T:function(a){v.j[(a-2)/2]=null},h:function(a){v.h.v||(v.h.v={});v.h.v[a]||(v.h.v[a]=1,d.k(a))},
t:{},ma:function(a,b){assert(b);v.t[b]||(v.t[b]={});var c=v.t[b];c[a]||(c[a]=1===b.length?function(){return v.q(b,a)}:2===b.length?function(c){return v.q(b,a,[c])}:function(){return v.q(b,a,Array.prototype.slice.call(arguments))});return c[a]},la:function(){throw"You must build with -s RETAIN_COMPILER_SETTINGS=1 for Runtime.getCompilerSetting or emscripten_get_compiler_setting to work";},G:function(a){var b=u;u=u+a|0;u=u+15&-16;return b},H:function(a){var b=w;w=w+a|0;w=w+15&-16;return b},D:function(a){var b=
y[B>>2];a=(b+a+15|0)&-16;y[B>>2]=a;if(a=a>=C)ka(),a=!0;return a?(y[B>>2]=b,0):b},A:function(a,b){return Math.ceil(a/(b?b:16))*(b?b:16)},ta:function(a,b,c){return c?+(a>>>0)+4294967296*+(b>>>0):+(a>>>0)+4294967296*+(b|0)},o:1024,p:4,ba:0};v.addFunction=v.J;v.removeFunction=v.T;var la=0;function assert(a,b){a||D("Assertion failed: "+b)}
function ma(a){var b;b="i32";"*"===b.charAt(b.length-1)&&(b="i32");switch(b){case "i1":return E[a>>0];case "i8":return E[a>>0];case "i16":return F[a>>1];case "i32":return y[a>>2];case "i64":return y[a>>2];case "float":return na[a>>2];case "double":return oa[a>>3];default:D("invalid type for setValue: "+b)}return null}
function G(a,b,c){var e,f,h;"number"===typeof a?(f=!0,h=a):(f=!1,h=a.length);var g="string"===typeof b?b:null,k;4==c?k=e:k=["function"===typeof H?H:v.H,v.G,v.H,v.D][void 0===c?2:c](Math.max(h,g?1:b.length));if(f){e=k;assert(0==(k&3));for(a=k+(h&-4);e<a;e+=4)y[e>>2]=0;for(a=k+h;e<a;)E[e++>>0]=0;return k}if("i8"===g)return a.subarray||a.slice?J.set(a,k):J.set(new Uint8Array(a),k),k;e=0;for(var l,m;e<h;){var p=a[e];"function"===typeof p&&(p=v.na(p));c=g||b[e];if(0===c)e++;else{"i64"==c&&(c="i32");f=
k+e;var r=c,r=r||"i8";"*"===r.charAt(r.length-1)&&(r="i32");switch(r){case "i1":E[f>>0]=p;break;case "i8":E[f>>0]=p;break;case "i16":F[f>>1]=p;break;case "i32":y[f>>2]=p;break;case "i64":tempI64=[p>>>0,(tempDouble=p,1<=+pa(tempDouble)?0<tempDouble?(qa(+ra(tempDouble/4294967296),4294967295)|0)>>>0:~~+sa((tempDouble-+(~~tempDouble>>>0))/4294967296)>>>0:0)];y[f>>2]=tempI64[0];y[f+4>>2]=tempI64[1];break;case "float":na[f>>2]=p;break;case "double":oa[f>>3]=p;break;default:D("invalid type for setValue: "+
r)}m!==c&&(l=v.F(c),m=c);e+=l}}return k}function K(a){var b;if(0===b||!a)return"";for(var c=0,e,f=0;;){e=J[a+f>>0];c|=e;if(0==e&&!b)break;f++;if(b&&f==b)break}b||(b=f);e="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,J.subarray(a,a+Math.min(b,1024))),e=e?e+c:c,a+=1024,b-=1024;return e}return d.UTF8ToString(a)}var ta="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ua(a,b,c,e){if(!(0<e))return 0;var f=c;e=c+e-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);55296<=g&&57343>=g&&(g=65536+((g&1023)<<10)|a.charCodeAt(++h)&1023);if(127>=g){if(c>=e)break;b[c++]=g}else{if(2047>=g){if(c+1>=e)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=e)break;b[c++]=224|g>>12}else{if(2097151>=g){if(c+3>=e)break;b[c++]=240|g>>18}else{if(67108863>=g){if(c+4>=e)break;b[c++]=248|g>>24}else{if(c+5>=e)break;b[c++]=252|g>>30;b[c++]=128|g>>24&63}b[c++]=128|g>>18&63}b[c++]=128|
g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-f}function va(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:2097151>=e?b+4:67108863>=e?b+5:b+6}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");
function wa(a){return a.replace(/__Z[\w\d_]+/g,function(a){var c;a:{var e=d.___cxa_demangle||d.__cxa_demangle;if(e)try{var f=a.substr(1),h=va(f)+1,g=H(h);ua(f,J,g,h);var k=H(4),l=e(g,0,0,k);if(0===ma(k)&&l){c=K(l);break a}}catch(m){}finally{g&&L(g),k&&L(k),l&&L(l)}else v.h("warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling");c=a}return a===c?a:a+" ["+c+"]"})}
function xa(){var a;a:{a=Error();if(!a.stack){try{throw Error(0);}catch(b){a=b}if(!a.stack){a="(no stack trace available)";break a}}a=a.stack.toString()}d.extraStackTrace&&(a+="\n"+d.extraStackTrace());return wa(a)}var buffer,E,J,F,ya,y,N,na,oa;
function za(){d.HEAP8=E=new Int8Array(buffer);d.HEAP16=F=new Int16Array(buffer);d.HEAP32=y=new Int32Array(buffer);d.HEAPU8=J=new Uint8Array(buffer);d.HEAPU16=ya=new Uint16Array(buffer);d.HEAPU32=N=new Uint32Array(buffer);d.HEAPF32=na=new Float32Array(buffer);d.HEAPF64=oa=new Float64Array(buffer)}var Aa,w,Ba,u,Ca,Da,B;Aa=w=Ba=u=Ca=Da=B=0;
function ka(){D("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+C+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var Ea=d.TOTAL_STACK||5242880,C=d.TOTAL_MEMORY||16777216;C<Ea&&d.k("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+C+"! (TOTAL_STACK="+Ea+")");
d.buffer?buffer=d.buffer:"object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(d.wasmMemory=new WebAssembly.Memory({initial:C/65536,maximum:C/65536}),buffer=d.wasmMemory.buffer):buffer=new ArrayBuffer(C);za();y[0]=1668509029;F[1]=25459;if(115!==J[2]||99!==J[3])throw"Runtime error: expected the system to be little-endian!";d.HEAP=void 0;d.buffer=buffer;d.HEAP8=E;d.HEAP16=F;d.HEAP32=y;d.HEAPU8=J;d.HEAPU16=ya;d.HEAPU32=N;d.HEAPF32=na;d.HEAPF64=oa;
function Fa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.s;"number"===typeof c?void 0===b.i?d.dynCall_v(c):d.dynCall_vi(c,b.i):c(void 0===b.i?null:b.i)}}}var Ga=[],Ha=[],Ia=[],Ja=[],Ka=[],La=!1;function Ma(){var a=d.preRun.shift();Ga.unshift(a)}function Na(a,b){var c=Array(va(a)+1),e=ua(a,c,0,c.length);b&&(c.length=e);return c}Math.imul&&-5===Math.imul(4294967295,5)||(Math.imul=function(a,b){var c=a&65535,e=b&65535;return c*e+((a>>>16)*e+c*(b>>>16)<<16)|0});
Math.pa=Math.imul;if(!Math.fround){var Oa=new Float32Array(1);Math.fround=function(a){Oa[0]=a;return Oa[0]}}Math.ja=Math.fround;Math.clz32||(Math.clz32=function(a){a=a>>>0;for(var b=0;32>b;b++)if(a&1<<31-b)return b;return 32});Math.fa=Math.clz32;Math.trunc||(Math.trunc=function(a){return 0>a?Math.ceil(a):Math.floor(a)});Math.trunc=Math.trunc;var pa=Math.abs,sa=Math.ceil,ra=Math.floor,qa=Math.min,O=0,Pa=null,Qa=null;function Ra(){O++;d.monitorRunDependencies&&d.monitorRunDependencies(O)}
function Sa(){O--;d.monitorRunDependencies&&d.monitorRunDependencies(O);if(0==O&&(null!==Pa&&(clearInterval(Pa),Pa=null),Qa)){var a=Qa;Qa=null;a()}}d.preloadedImages={};d.preloadedAudios={};var P=null;
(function(a){function b(a,b){var c=r;if(0>a.indexOf("."))c=(c||{})[a];else var e=a.split("."),c=(c||{})[e[0]],c=(c||{})[e[1]];b&&(c=(c||{})[b]);void 0===c&&D("bad lookupImport to ("+a+")."+b);return c}function c(b){var c=a.buffer;b.byteLength<c.byteLength&&a.printErr("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");var c=new Int8Array(c),e=new Int8Array(b);P||c.set(e.subarray(a.STATIC_BASE,a.STATIC_BASE+a.STATIC_BUMP),a.STATIC_BASE);e.set(c);
d.buffer=buffer=b;za()}function e(){var b;if(a.wasmBinary)b=a.wasmBinary,b=new Uint8Array(b);else if(a.readBinary)b=a.readBinary(m);else throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";return b}function f(){return a.wasmBinary||"function"!==typeof fetch?new Promise(function(a){a(e())}):fetch(m).then(function(a){return a.arrayBuffer()})}function h(b,c,e){if("function"!==typeof a.asm||a.asm===
z)a.asmPreload?a.asm=a.asmPreload:eval(a.read(p));return"function"!==typeof a.asm?(a.printErr("asm evalling did not set the module properly"),!1):a.asm(b,c,e)}function g(b,e){function z(b){M=b.exports;M.memory&&c(M.memory);a.asm=M;a.usingWasm=!0;Sa()}if("object"!==typeof WebAssembly)return a.printErr("no native wasm support detected"),!1;if(!(a.wasmMemory instanceof WebAssembly.Memory))return a.printErr("no native wasm Memory in use"),!1;e.memory=a.wasmMemory;r.global={NaN:NaN,Infinity:Infinity};
r["global.Math"]=b.Math;r.env=e;Ra();if(a.instantiateWasm)try{return a.instantiateWasm(r,z)}catch(g){return a.printErr("Module.instantiateWasm callback failed with error: "+g),!1}a.printErr("asynchronously preparing wasm");f().then(function(a){return WebAssembly.instantiate(a,r)}).then(function(a){z(a.instance)}).catch(function(b){a.printErr("failed to asynchronously prepare wasm: "+b);a.quit(1,b)});return{}}var k=a.wasmJSMethod||"native-wasm";a.wasmJSMethod=k;var l=a.wasmTextFile||"re2.wast",m=a.wasmBinaryFile||
"re2.wasm",p=a.asmjsCodeFile||"re2.temp.asm.js",r={global:null,env:null,asm2wasm:{"f64-rem":function(a,b){return a%b},"f64-to-int":function(a){return a|0},"i32s-div":function(a,b){return(a|0)/(b|0)|0},"i32u-div":function(a,b){return(a>>>0)/(b>>>0)>>>0},"i32s-rem":function(a,b){return(a|0)%(b|0)|0},"i32u-rem":function(a,b){return(a>>>0)%(b>>>0)>>>0},"debugger":function(){debugger}},parent:a},M=null;a.asmPreload=a.asm;a.reallocBuffer=function(b){var c=a.usingWasm?65536:16777216;0<b%c&&(b+=c-b%c);var c=
a.buffer,e=c.byteLength;if(a.usingWasm)try{return-1!==a.wasmMemory.grow((b-e)/65536)?a.buffer=a.wasmMemory.buffer:null}catch(f){return null}else return M.__growWasmMemory((b-e)/65536),a.buffer!==c?a.buffer:null};a.asm=function(f,z,m){if(!z.table){var R=a.wasmTableSize;void 0===R&&(R=1024);var ea=a.wasmMaxTableSize;z.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==ea?new WebAssembly.Table({initial:R,maximum:ea,element:"anyfunc"}):new WebAssembly.Table({initial:R,
element:"anyfunc"}):Array(R);a.wasmTable=z.table}z.memoryBase||(z.memoryBase=a.STATIC_BASE);z.tableBase||(z.tableBase=0);for(var t,R=k.split(","),ea=0;ea<R.length;ea++)if(t=R[ea],a.printErr("trying binaryen method: "+t),"native-wasm"===t){if(t=g(f,z))break}else if("asmjs"===t){if(t=h(f,z,m))break}else if("interpret-asm2wasm"===t||"interpret-s-expr"===t||"interpret-binary"===t){var I=f,A=z,fa=m;if("function"!==typeof WasmJS)a.printErr("WasmJS not detected - polyfill not bundled?"),t=!1;else{var x=
WasmJS({});x.outside=a;x.info=r;x.lookupImport=b;assert(fa===a.buffer);r.global=I;r.env=A;assert(fa===a.buffer);A.memory=fa;assert(A.memory instanceof ArrayBuffer);x.providedTotalMemory=a.buffer.byteLength;I=void 0;I="interpret-binary"===t?e():a.read("interpret-asm2wasm"==t?p:l);A=void 0;if("interpret-asm2wasm"==t)A=x._malloc(I.length+1),x.writeAsciiToMemory(I,A),x._load_asm2wasm(A);else if("interpret-s-expr"===t)A=x._malloc(I.length+1),x.writeAsciiToMemory(I,A),x._load_s_expr2wasm(A);else if("interpret-binary"===
t)A=x._malloc(I.length),x.HEAPU8.set(I,A),x._load_binary2wasm(A,I.length);else throw"what? "+t;x._free(A);x._instantiate(A);a.newBuffer&&(c(a.newBuffer),a.newBuffer=null);t=M=x.asmExports}if(t)break}else throw"bad method: "+t;if(!t)throw"no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods";a.printErr("binaryen method succeeded.");return t};var z=a.asm})(d);Aa=v.o;w=Aa+59104;
Ha.push({s:function(){Ta()}},{s:function(){Ua()}});P=0<=d.wasmJSMethod.indexOf("asmjs")||0<=d.wasmJSMethod.indexOf("interpret-asm2wasm")?"re2.js.mem":null;d.STATIC_BASE=Aa;d.STATIC_BUMP=59104;var Va=w;w+=16;function Wa(a,b){Ja.unshift({s:a,i:b})}function Xa(){for(var a=Array(256),b=0;256>b;++b)a[b]=String.fromCharCode(b);Ya=a}var Ya=void 0;function Q(a){for(var b="";J[a];)b+=Ya[J[a++]];return b}var Za={},$a={},ab={};
function bb(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function cb(a,b){a=bb(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function db(a,b){var c=cb(b,function(a){this.name=b;this.message=a;a=Error(a).stack;void 0!==a&&(this.stack=this.toString()+"\n"+a.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var eb=void 0;function S(a){throw new eb(a);}var fb=void 0;function gb(a){throw new fb(a);}
function hb(a,b,c){function e(b){b=c(b);b.length!==a.length&&gb("Mismatched type converter count");for(var e=0;e<a.length;++e)T(a[e],b[e])}a.forEach(function(a){ab[a]=b});var f=Array(b.length),h=[],g=0;b.forEach(function(a,b){$a.hasOwnProperty(a)?f[b]=$a[a]:(h.push(a),Za.hasOwnProperty(a)||(Za[a]=[]),Za[a].push(function(){f[b]=$a[a];++g;g===h.length&&e(f)}))});0===h.length&&e(f)}
function T(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var e=b.name;a||S('type "'+e+'" must have a positive integer typeid pointer');if($a.hasOwnProperty(a)){if(c.R)return;S("Cannot register type '"+e+"' twice")}$a[a]=b;delete ab[a];Za.hasOwnProperty(a)&&(b=Za[a],delete Za[a],b.forEach(function(a){a()}))}function ib(){return!!ib.a}var jb=0,kb=[],U={};
function lb(){var a=jb;if(!a)return(v.g(0),0)|0;var b=U[a],c=b.type;if(!c)return(v.g(0),a)|0;var e=Array.prototype.slice.call(arguments);d.___cxa_is_pointer_type(c);lb.buffer||(lb.buffer=H(4));y[lb.buffer>>2]=a;for(var a=lb.buffer,f=0;f<e.length;f++)if(e[f]&&d.___cxa_can_catch(e[f],c,a))return a=y[a>>2],b.w=a,(v.g(e[f]),a)|0;a=y[a>>2];return(v.g(c),a)|0}d._memset=mb;
function nb(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}d._pthread_mutex_lock=ob;function pb(a){return 0===a%4&&(0!==a%100||0===a%400)}function qb(a,b){for(var c=0,e=0;e<=b;c+=a[e++]);return c}var rb=[31,29,31,30,31,30,31,31,30,31,30,31],sb=[31,28,31,30,31,30,31,31,30,31,30,31];
function tb(a,b){for(var c=new Date(a.getTime());0<b;){var e=c.getMonth(),f=(pb(c.getFullYear())?rb:sb)[e];if(b>f-c.getDate())b-=f-c.getDate()+1,c.setDate(1),11>e?c.setMonth(e+1):(c.setMonth(0),c.setFullYear(c.getFullYear()+1));else{c.setDate(c.getDate()+b);break}}return c}
function ub(a,b,c,e){function f(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function h(a,b){return f(a,b,"0")}function g(a,b){function c(a){return 0>a?-1:0<a?1:0}var e;0===(e=c(a.getFullYear()-b.getFullYear()))&&0===(e=c(a.getMonth()-b.getMonth()))&&(e=c(a.getDate()-b.getDate()));return e}function k(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function l(a){a=tb(new Date(a.b+1900,0,1),a.m);var b=k(new Date(a.getFullYear()+1,0,4));return 0>=g(k(new Date(a.getFullYear(),0,4)),a)?0>=g(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var m=y[e+40>>2];e={Z:y[e>>2],Y:y[e+4>>2],l:y[e+8>>2],f:y[e+12>>2],e:y[e+16>>2],b:y[e+20>>2],I:y[e+24>>2],m:y[e+28>>2],za:y[e+32>>2],X:y[e+36>>2],$:m?K(m):""};
c=K(c);var m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"},p;for(p in m)c=c.replace(new RegExp(p,"g"),m[p]);var r="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),M="January February March April May June July August September October November December".split(" "),m={"%a":function(a){return r[a.I].substring(0,3)},"%A":function(a){return r[a.I]},"%b":function(a){return M[a.e].substring(0,
3)},"%B":function(a){return M[a.e]},"%C":function(a){return h((a.b+1900)/100|0,2)},"%d":function(a){return h(a.f,2)},"%e":function(a){return f(a.f,2," ")},"%g":function(a){return l(a).toString().substring(2)},"%G":function(a){return l(a)},"%H":function(a){return h(a.l,2)},"%I":function(a){a=a.l;0==a?a=12:12<a&&(a-=12);return h(a,2)},"%j":function(a){return h(a.f+qb(pb(a.b+1900)?rb:sb,a.e-1),3)},"%m":function(a){return h(a.e+1,2)},"%M":function(a){return h(a.Y,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=
a.l&&12>a.l?"AM":"PM"},"%S":function(a){return h(a.Z,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.b+1900,a.e+1,a.f,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.b+1900,0,1),c=0===b.getDay()?b:tb(b,7-b.getDay());a=new Date(a.b+1900,a.e,a.f);return 0>g(c,a)?h(Math.ceil((31-c.getDate()+(qb(pb(a.getFullYear())?rb:sb,a.getMonth()-1)-31)+a.getDate())/7),2):0===g(c,b)?"01":"00"},"%V":function(a){var b=k(new Date(a.b+1900,0,4)),c=k(new Date(a.b+1901,0,4)),e=tb(new Date(a.b+
1900,0,1),a.m);return 0>g(e,b)?"53":0>=g(c,e)?"01":h(Math.ceil((b.getFullYear()<a.b+1900?a.m+32-b.getDate():a.m+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.b+1900,a.e+1,a.f,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.b,0,1),c=1===b.getDay()?b:tb(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.b+1900,a.e,a.f);return 0>g(c,a)?h(Math.ceil((31-c.getDate()+(qb(pb(a.getFullYear())?rb:sb,a.getMonth()-1)-31)+a.getDate())/7),2):0===g(c,b)?"01":"00"},"%y":function(a){return(a.b+1900).toString().substring(2)},
"%Y":function(a){return a.b+1900},"%z":function(a){a=a.X;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.$},"%%":function(){return"%"}};for(p in m)0<=c.indexOf(p)&&(c=c.replace(new RegExp(p,"g"),m[p](e)));p=Na(c,!1);if(p.length>b)return 0;E.set(p,a);return p.length-1}function L(){}d._free=L;function H(a){return v.D(a+8)+8&4294967288}d._malloc=H;function vb(a){return this.fromWireType(N[a>>2])}
function wb(a,b){wb.a||(wb.a={});a in wb.a||(d.dynCall_v(b),wb.a[a]=1)}var xb={},yb=1;function zb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Ab(a,b,c){switch(b){case 0:return c?function(a){return E[a]}:function(a){return J[a]};case 1:return c?function(a){return F[a>>1]}:function(a){return ya[a>>1]};case 2:return c?function(a){return y[a>>2]}:function(a){return N[a>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Bb=[],V=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Cb(a){4<a&&0===--V[a].u&&(V[a]=void 0,Bb.push(a))}function Db(){for(var a=0,b=5;b<V.length;++b)void 0!==V[b]&&++a;return a}
function Eb(){for(var a=5;a<V.length;++a)if(void 0!==V[a])return V[a];return null}function Fb(){d.count_emval_handles=Db;d.get_first_emval=Eb}function Gb(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Bb.length?Bb.pop():V.length;V[b]={u:1,value:a};return b}}var W=0;function X(){W+=4;return y[W-4>>2]}var Hb={};
function Ib(a,b){switch(b){case 2:return function(a){return this.fromWireType(na[a>>2])};case 3:return function(a){return this.fromWireType(oa[a>>3])};default:throw new TypeError("Unknown float type: "+a);}}d._pthread_cond_broadcast=Jb;var Kb=w;w+=16;
function Lb(a){var b,c;Lb.a?(c=y[Kb>>2],b=y[c>>2]):(Lb.a=!0,Y.USER=Y.LOGNAME="web_user",Y.PATH="/",Y.PWD="/",Y.HOME="/home/web_user",Y.LANG="C",Y._=d.thisProgram,b=G(1024,"i8",2),c=G(256,"i8*",2),y[c>>2]=b,y[Kb>>2]=c);var e=[],f=0,h;for(h in a)if("string"===typeof a[h]){var g=h+"="+a[h];e.push(g);f+=g.length}if(1024<f)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(a=0;a<e.length;a++){f=g=e[a];h=b;for(var k=0;k<f.length;++k)E[h++>>0]=f.charCodeAt(k);E[h>>0]=0;y[c+4*a>>2]=b;b+=g.length+
1}y[c+4*e.length>>2]=0}var Y={};function Mb(a){if(0===a)return 0;a=K(a);if(!Y.hasOwnProperty(a))return 0;Mb.a&&L(Mb.a);Mb.a=G(Na(Y[a]),"i8",0);return Mb.a}function Nb(a,b){if(!(a instanceof Function))throw new TypeError("new_ called with constructor type "+typeof a+" which is not a function");var c=cb(a.name||"unknownFunctionName",function(){});c.prototype=a.prototype;var c=new c,e=a.apply(c,b);return e instanceof Object?e:c}function Ob(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function Pb(a,b,c,e,f){var h=b.length;2>h&&S("argTypes array size mismatch! Must at least get return value and 'this' types!");var g=null!==b[1]&&null!==c,k="",l="";for(c=0;c<h-2;++c)k+=(0!==c?", ":"")+"arg"+c,l+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+bb(a)+"("+k+") {\nif (arguments.length !== "+(h-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+(h-2)+" args!');\n}\n";var m=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].d){m=
!0;break}m&&(a+="var destructors = [];\n");var p=m?"destructors":"null",k="throwBindingError invoker fn runDestructors retType classParam".split(" ");e=[S,e,f,Ob,b[0],b[1]];g&&(a+="var thisWired = classParam.toWireType("+p+", this);\n");for(c=0;c<h-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+p+", arg"+c+"); // "+b[c+2].name+"\n",k.push("argType"+c),e.push(b[c+2]);g&&(l="thisWired"+(0<l.length?", ":"")+l);h="void"!==b[0].name;a+=(h?"var rv = ":"")+"invoker(fn"+(0<l.length?", ":"")+l+");\n";
if(m)a+="runDestructors(destructors);\n";else for(c=g?1:2;c<b.length;++c)g=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].d&&(a+=g+"_dtor("+g+"); // "+b[c].name+"\n",k.push(g+"_dtor"),e.push(b[c].d));h&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");k.push(a+"}\n");return Nb(Function,k).apply(null,e)}
function Qb(a,b,c){if(void 0===a[b].c){var e=a[b];a[b]=function(){a[b].c.hasOwnProperty(arguments.length)||S("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].c+")!");return a[b].c[arguments.length].apply(this,arguments)};a[b].c=[];a[b].c[e.K]=e}}
function Rb(a,b,c){d.hasOwnProperty(a)?((void 0===c||void 0!==d[a].c&&void 0!==d[a].c[c])&&S("Cannot register public name '"+a+"' twice"),Qb(d,a,a),d.hasOwnProperty(c)&&S("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),d[a].c[c]=b):(d[a]=b,void 0!==c&&(d[a].wa=c))}function Sb(a,b){for(var c=[],e=0;e<a;e++)c.push(y[(b>>2)+e]);return c}
function Tb(a,b,c){d.hasOwnProperty(a)||gb("Replacing nonexistant public symbol");void 0!==d[a].c&&void 0!==c?d[a].c[c]=b:(d[a]=b,d[a].K=c)}
function Ub(a,b){a=Q(a);var c;if(void 0!==d["FUNCTION_TABLE_"+a])c=d["FUNCTION_TABLE_"+a][b];else if("undefined"!==typeof FUNCTION_TABLE)c=FUNCTION_TABLE[b];else{c=d.asm["dynCall_"+a];void 0===c&&(c=d.asm["dynCall_"+a.replace(/f/g,"d")],void 0===c&&S("No dynCall invoker for signature: "+a));for(var e=[],f=1;f<a.length;++f)e.push("a"+f);f="return function "+("dynCall_"+a+"_"+b)+"("+e.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(e.length?", ":"")+e.join(", ")+");\n";c=(new Function("dynCall",
"rawFunction",f+"};\n"))(c,b)}"function"!==typeof c&&S("unknown function pointer with signature "+a+": "+b);return c}var Vb=void 0;function Wb(a){a=Xb(a);var b=Q(a);L(a);return b}function Yb(a,b){function c(a){f[a]||$a[a]||(ab[a]?ab[a].forEach(c):(e.push(a),f[a]=!0))}var e=[],f={};b.forEach(c);throw new Vb(a+": "+e.map(Wb).join([", "]));}function Zb(a){d.___errno_location&&(y[d.___errno_location()>>2]=a);return a}d._memcpy=$b;
var ac=G([8,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,6,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,7,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,6,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,5,0,1,0,2,0,1,0,3,0,1,0,2,0,1,0,4,0,1,0,2,0,
1,0,3,0,1,0,2,0,1,0],"i8",2);function bc(a){a=a|0;var b=0,b=E[ac+(a&255)>>0]|0;if(8>(b|0))return b|0;b=E[ac+(a>>8&255)>>0]|0;if(8>(b|0))return b+8|0;b=E[ac+(a>>16&255)>>0]|0;return 8>(b|0)?b+16|0:(E[ac+(a>>>24)>>0]|0)+24|0}d._sbrk=cc;d._memmove=dc;d._pthread_mutex_unlock=ec;d._llvm_bswap_i32=fc;
function Z(a,b){W=b;try{var c=X(),e=X(),f=X(),h=0;Z.buffer||(Z.a=[null,[],[]],Z.B=function(a,b){var c=Z.a[a];assert(c);if(0===b||10===b){var e=1===a?d.print:d.printErr,f;a:{for(var g=f=0;c[g];)++g;if(16<g-f&&c.subarray&&ta)f=ta.decode(c.subarray(f,g));else for(var h,k,l,m,p,fa,g="";;){h=c[f++];if(!h){f=g;break a}h&128?(k=c[f++]&63,192==(h&224)?g+=String.fromCharCode((h&31)<<6|k):(l=c[f++]&63,224==(h&240)?h=(h&15)<<12|k<<6|l:(m=c[f++]&63,240==(h&248)?h=(h&7)<<18|k<<12|l<<6|m:(p=c[f++]&63,248==(h&252)?
h=(h&3)<<24|k<<18|l<<12|m<<6|p:(fa=c[f++]&63,h=(h&1)<<30|k<<24|l<<18|m<<12|p<<6|fa))),65536>h?g+=String.fromCharCode(h):(h-=65536,g+=String.fromCharCode(55296|h>>10,56320|h&1023)))):g+=String.fromCharCode(h)}}e(f);c.length=0}else c.push(b)});for(var g=0;g<f;g++){for(var k=y[e+8*g>>2],l=y[e+(8*g+4)>>2],m=0;m<l;m++)Z.B(c,J[k+m]);h+=l}return h}catch(p){return"undefined"!==typeof FS&&p instanceof FS.n||D(p),-p.r}}var gc=w;w+=16;Xa();eb=d.BindingError=db(Error,"BindingError");
fb=d.InternalError=db(Error,"InternalError");Fb();Lb(Y);Vb=d.UnboundTypeError=db(Error,"UnboundTypeError");Ja.push(function(){var a=d._fflush;a&&a(0);if(a=Z.B){var b=Z.a;b[1].length&&a(1,10);b[2].length&&a(2,10)}});B=G(1,"i32",2);Ba=u=v.A(w);Ca=Ba+Ea;Da=v.A(Ca);y[B>>2]=Da;d.wasmTableSize=524;d.wasmMaxTableSize=524;
d.L={Math:Math,Int8Array:Int8Array,Int16Array:Int16Array,Int32Array:Int32Array,Uint8Array:Uint8Array,Uint16Array:Uint16Array,Uint32Array:Uint32Array,Float32Array:Float32Array,Float64Array:Float64Array,NaN:NaN,Infinity:Infinity};
d.M={abort:D,assert:assert,enlargeMemory:function(){ka()},getTotalMemory:function(){return C},abortOnCannotGrowMemory:ka,invoke_iiiiiiii:function(a,b,c,e,f,h,g,k){try{return d.dynCall_iiiiiiii(a,b,c,e,f,h,g,k)}catch(l){if("number"!==typeof l&&"longjmp"!==l)throw l;d.setThrew(1,0)}},invoke_iiii:function(a,b,c,e){try{return d.dynCall_iiii(a,b,c,e)}catch(f){if("number"!==typeof f&&"longjmp"!==f)throw f;d.setThrew(1,0)}},invoke_viiiii:function(a,b,c,e,f,h){try{d.dynCall_viiiii(a,b,c,e,f,h)}catch(g){if("number"!==
typeof g&&"longjmp"!==g)throw g;d.setThrew(1,0)}},invoke_viiiiiii:function(a,b,c,e,f,h,g,k){try{d.dynCall_viiiiiii(a,b,c,e,f,h,g,k)}catch(l){if("number"!==typeof l&&"longjmp"!==l)throw l;d.setThrew(1,0)}},invoke_iiiiiid:function(a,b,c,e,f,h,g){try{return d.dynCall_iiiiiid(a,b,c,e,f,h,g)}catch(k){if("number"!==typeof k&&"longjmp"!==k)throw k;d.setThrew(1,0)}},invoke_vi:function(a,b){try{d.dynCall_vi(a,b)}catch(c){if("number"!==typeof c&&"longjmp"!==c)throw c;d.setThrew(1,0)}},invoke_vii:function(a,
b,c){try{d.dynCall_vii(a,b,c)}catch(e){if("number"!==typeof e&&"longjmp"!==e)throw e;d.setThrew(1,0)}},invoke_iiiiiii:function(a,b,c,e,f,h,g){try{return d.dynCall_iiiiiii(a,b,c,e,f,h,g)}catch(k){if("number"!==typeof k&&"longjmp"!==k)throw k;d.setThrew(1,0)}},invoke_iiiiid:function(a,b,c,e,f,h){try{return d.dynCall_iiiiid(a,b,c,e,f,h)}catch(g){if("number"!==typeof g&&"longjmp"!==g)throw g;d.setThrew(1,0)}},invoke_ii:function(a,b){try{return d.dynCall_ii(a,b)}catch(c){if("number"!==typeof c&&"longjmp"!==
c)throw c;d.setThrew(1,0)}},invoke_viijii:function(a,b,c,e,f,h,g){try{d.dynCall_viijii(a,b,c,e,f,h,g)}catch(k){if("number"!==typeof k&&"longjmp"!==k)throw k;d.setThrew(1,0)}},invoke_iiiiij:function(a,b,c,e,f,h,g){try{return d.dynCall_iiiiij(a,b,c,e,f,h,g)}catch(k){if("number"!==typeof k&&"longjmp"!==k)throw k;d.setThrew(1,0)}},invoke_viii:function(a,b,c,e){try{d.dynCall_viii(a,b,c,e)}catch(f){if("number"!==typeof f&&"longjmp"!==f)throw f;d.setThrew(1,0)}},invoke_v:function(a){try{d.dynCall_v(a)}catch(b){if("number"!==
typeof b&&"longjmp"!==b)throw b;d.setThrew(1,0)}},invoke_iiiiiiiii:function(a,b,c,e,f,h,g,k,l){try{return d.dynCall_iiiiiiiii(a,b,c,e,f,h,g,k,l)}catch(m){if("number"!==typeof m&&"longjmp"!==m)throw m;d.setThrew(1,0)}},invoke_iiiii:function(a,b,c,e,f){try{return d.dynCall_iiiii(a,b,c,e,f)}catch(h){if("number"!==typeof h&&"longjmp"!==h)throw h;d.setThrew(1,0)}},invoke_viiiiii:function(a,b,c,e,f,h,g){try{d.dynCall_viiiiii(a,b,c,e,f,h,g)}catch(k){if("number"!==typeof k&&"longjmp"!==k)throw k;d.setThrew(1,
0)}},invoke_iii:function(a,b,c){try{return d.dynCall_iii(a,b,c)}catch(e){if("number"!==typeof e&&"longjmp"!==e)throw e;d.setThrew(1,0)}},invoke_iiiiii:function(a,b,c,e,f,h){try{return d.dynCall_iiiiii(a,b,c,e,f,h)}catch(g){if("number"!==typeof g&&"longjmp"!==g)throw g;d.setThrew(1,0)}},invoke_viiii:function(a,b,c,e,f){try{d.dynCall_viiii(a,b,c,e,f)}catch(h){if("number"!==typeof h&&"longjmp"!==h)throw h;d.setThrew(1,0)}},_strftime:ub,_pthread_cond_wait:function(){return 0},___lock:function(){},floatReadValueFromPointer:Ib,
simpleReadValueFromPointer:vb,_pthread_rwlock_wrlock:function(){return 0},__embind_register_memory_view:function(a,b,c){function e(a){a=a>>2;var b=N;return new f(b.buffer,b[a+1],b[a])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=Q(c);T(a,{name:c,fromWireType:e,argPackAdvance:8,readValueFromPointer:e},{R:!0})},throwInternalError:gb,get_first_emval:Eb,_abort:function(){d.abort()},whenDependentTypesAreResolved:hb,___gxx_personality_v0:function(){},
__embind_register_integer:function(a,b,c,e,f){function h(a){return a}b=Q(b);-1===f&&(f=4294967295);var g=nb(c);if(0===e)var k=32-8*c,h=function(a){return a<<k>>>k};T(a,{name:b,fromWireType:h,toWireType:function(a,c){if("number"!==typeof c&&"boolean"!==typeof c)throw new TypeError('Cannot convert "'+zb(c)+'" to '+this.name);if(c<e||c>f)throw new TypeError('Passing a number "'+zb(c)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+e+", "+f+"]!");return c|
0},argPackAdvance:8,readValueFromPointer:Ab(b,g,0!==e),d:null})},__embind_register_void:function(a,b){b=Q(b);T(a,{qa:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},___assert_fail:function(a,b,c,e){la=!0;throw"Assertion failed: "+K(a)+", at: "+[b?K(b):"unknown filename",c,e?K(e):"unknown function"]+" at "+xa();},_pthread_rwlock_unlock:function(){return 0},___cxa_allocate_exception:function(a){return H(a)},___cxa_find_matching_catch:lb,extendError:db,___buildEnvironment:Lb,
getShiftFromSize:nb,_pthread_rwlock_destroy:function(){return 0},___syscall91:function(a,b){W=b;try{var c=X(),e=X(),f=Hb.S[c];if(!f)return 0;if(e===f.ra){var h=FS.oa(f.fd);Hb.ha(c,h,e,f.flags);FS.va(h);Hb.S[c]=null;f.da&&L(f.ua)}return 0}catch(g){return"undefined"!==typeof FS&&g instanceof FS.n||D(g),-g.r}},__addDays:tb,_strftime_l:function(a,b,c,e){return ub(a,b,c,e)},_llvm_cttz_i32:bc,___setErrNo:Zb,__emval_register:Gb,__embind_register_std_wstring:function(a,b,c){c=Q(c);var e,f;2===b?(e=function(){return ya},
f=1):4===b&&(e=function(){return N},f=2);T(a,{name:c,fromWireType:function(a){for(var b=e(),c=N[a>>2],l=Array(c),m=a+4>>f,p=0;p<c;++p)l[p]=String.fromCharCode(b[m+p]);L(a);return l.join("")},toWireType:function(a,c){var k=e(),l=c.length,m=H(4+l*b);N[m>>2]=l;for(var p=m+4>>f,r=0;r<l;++r)k[p+r]=c.charCodeAt(r);null!==a&&a.push(L,m);return m},argPackAdvance:8,readValueFromPointer:vb,d:function(a){L(a)}})},_emscripten_memcpy_big:function(a,b,c){J.set(J.subarray(b,b+c),a);return a},__embind_register_bool:function(a,
b,c,e,f){var h=nb(c);b=Q(b);T(a,{name:b,fromWireType:function(a){return!!a},toWireType:function(a,b){return b?e:f},argPackAdvance:8,readValueFromPointer:function(a){var e;if(1===c)e=E;else if(2===c)e=F;else if(4===c)e=y;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(e[a>>h])},d:null})},___resumeException:function(a){jb||(jb=a);throw a+" - Exception catching is disabled, this exception cannot be caught. Compile with -s DISABLE_EXCEPTION_CATCHING=0 or DISABLE_EXCEPTION_CATCHING=2 to catch.";
},__ZSt18uncaught_exceptionv:ib,__embind_register_emval:function(a,b){b=Q(b);T(a,{name:b,fromWireType:function(a){var b=V[a].value;Cb(a);return b},toWireType:function(a,b){return Gb(b)},argPackAdvance:8,readValueFromPointer:vb,d:null})},getTypeName:Wb,___cxa_begin_catch:function(a){var b=U[a];b&&!b.C&&(b.C=!0,ib.a--);b&&(b.U=!1);kb.push(a);a:{if(a&&!U[a])for(var c in U)if(U[c].w===a){b=c;break a}b=a}b&&U[b].u++;return a},_pthread_getspecific:function(a){return xb[a]||0},createNamedFunction:cb,embind_init_charCodes:Xa,
readLatin1String:Q,_embind_repr:zb,throwUnboundTypeError:Yb,craftInvokerFunction:Pb,__emval_decref:Cb,_pthread_once:wb,_getenv:Mb,runDestructors:Ob,makeLegalFunctionName:bb,_pthread_key_create:function(a){if(0==a)return 22;y[a>>2]=yb;xb[yb]=0;yb++;return 0},___unlock:function(){},heap32VectorToArray:Sb,init_emval:Fb,__isLeapYear:pb,_llvm_cttz_i64:function(a,b){var c=bc(a);32==c&&(c+=bc(b));return(v.g(0),c)|0},_pthread_rwlock_init:function(){return 0},_pthread_setspecific:function(a,b){if(!(a in xb))return 22;
xb[a]=b;return 0},___cxa_atexit:function(){return Wa.apply(null,arguments)},integerReadValueFromPointer:Ab,registerType:T,___cxa_throw:function(a,b,c){U[a]={ya:a,w:a,type:b,ga:c,u:0,C:!1,U:!1};jb=a;"uncaught_exception"in ib?ib.a++:ib.a=1;throw a+" - Exception catching is disabled, this exception cannot be caught. Compile with -s DISABLE_EXCEPTION_CATCHING=0 or DISABLE_EXCEPTION_CATCHING=2 to catch.";},__embind_register_function:function(a,b,c,e,f,h){var g=Sb(b,c);a=Q(a);f=Ub(e,f);Rb(a,function(){Yb("Cannot call "+
a+" due to unbound types",g)},b-1);hb([],g,function(c){c=[c[0],null].concat(c.slice(1));Tb(a,Pb(a,c,null,f,h),b-1);return[]})},__arraySum:qb,___syscall6:function(a,b){W=b;try{var c=Hb.O();FS.close(c);return 0}catch(e){return"undefined"!==typeof FS&&e instanceof FS.n||D(e),-e.r}},throwBindingError:S,ensureOverloadTable:Qb,count_emval_handles:Db,requireFunction:Ub,__embind_register_float:function(a,b,c){c=nb(c);b=Q(b);T(a,{name:b,fromWireType:function(a){return a},toWireType:function(a,b){if("number"!==
typeof b&&"boolean"!==typeof b)throw new TypeError('Cannot convert "'+zb(b)+'" to '+this.name);return b},argPackAdvance:8,readValueFromPointer:Ib(b,c),d:null})},new_:Nb,_atexit:Wa,___syscall140:function(a,b){W=b;try{var c=Hb.O(),e=X(),f=X(),h=X(),g=X();assert(0===e);FS.sa(c,f,g);y[h>>2]=c.position;c.Q&&0===f&&0===g&&(c.Q=null);return 0}catch(k){return"undefined"!==typeof FS&&k instanceof FS.n||D(k),-k.r}},exposePublicSymbol:Rb,__embind_register_std_string:function(a,b){b=Q(b);T(a,{name:b,fromWireType:function(a){for(var b=
N[a>>2],f=Array(b),h=0;h<b;++h)f[h]=String.fromCharCode(J[a+4+h]);L(a);return f.join("")},toWireType:function(a,b){function f(a,b){return a[b]}function h(a,b){return a.charCodeAt(b)}b instanceof ArrayBuffer&&(b=new Uint8Array(b));var g;b instanceof Uint8Array?g=f:b instanceof Uint8ClampedArray?g=f:b instanceof Int8Array?g=f:"string"===typeof b?g=h:S("Cannot pass non-string to std::string");var k=b.length,l=H(4+k);N[l>>2]=k;for(var m=0;m<k;++m){var p=g(b,m);255<p&&(L(l),S("String has UTF-16 code units that do not fit in 8 bits"));
J[l+4+m]=p}null!==a&&a.push(L,l);return l},argPackAdvance:8,readValueFromPointer:vb,d:function(a){L(a)}})},replacePublicSymbol:Tb,___cxa_pure_virtual:function(){la=!0;throw"Pure virtual function called!";},___syscall146:Z,___map_file:function(){Zb(1);return-1},DYNAMICTOP_PTR:B,tempDoublePtr:Va,ABORT:la,STACKTOP:u,STACK_MAX:Ca,cttz_i8:ac,___dso_handle:gc};var hc=d.asm(d.L,d.M,buffer);d.asm=hc;var fc=d._llvm_bswap_i32=function(){return d.asm._llvm_bswap_i32.apply(null,arguments)};
d.setThrew=function(){return d.asm.setThrew.apply(null,arguments)};d.___cxa_is_pointer_type=function(){return d.asm.___cxa_is_pointer_type.apply(null,arguments)};var mb=d._memset=function(){return d.asm._memset.apply(null,arguments)},cc=d._sbrk=function(){return d.asm._sbrk.apply(null,arguments)},$b=d._memcpy=function(){return d.asm._memcpy.apply(null,arguments)};d.stackAlloc=function(){return d.asm.stackAlloc.apply(null,arguments)};d.getTempRet0=function(){return d.asm.getTempRet0.apply(null,arguments)};
var Ua=d.__GLOBAL__sub_I_bind_cpp=function(){return d.asm.__GLOBAL__sub_I_bind_cpp.apply(null,arguments)};d.setTempRet0=function(){return d.asm.setTempRet0.apply(null,arguments)};var ec=d._pthread_mutex_unlock=function(){return d.asm._pthread_mutex_unlock.apply(null,arguments)};d._emscripten_get_global_libc=function(){return d.asm._emscripten_get_global_libc.apply(null,arguments)};
var Xb=d.___getTypeName=function(){return d.asm.___getTypeName.apply(null,arguments)},Jb=d._pthread_cond_broadcast=function(){return d.asm._pthread_cond_broadcast.apply(null,arguments)};d.stackSave=function(){return d.asm.stackSave.apply(null,arguments)};d.___cxa_can_catch=function(){return d.asm.___cxa_can_catch.apply(null,arguments)};L=d._free=function(){return d.asm._free.apply(null,arguments)};d.runPostSets=function(){return d.asm.runPostSets.apply(null,arguments)};
d.establishStackSpace=function(){return d.asm.establishStackSpace.apply(null,arguments)};var dc=d._memmove=function(){return d.asm._memmove.apply(null,arguments)};d.stackRestore=function(){return d.asm.stackRestore.apply(null,arguments)};
var H=d._malloc=function(){return d.asm._malloc.apply(null,arguments)},ob=d._pthread_mutex_lock=function(){return d.asm._pthread_mutex_lock.apply(null,arguments)},Ta=d.__GLOBAL__sub_I_re2_binding_cc=function(){return d.asm.__GLOBAL__sub_I_re2_binding_cc.apply(null,arguments)};d.dynCall_iiiiiiii=function(){return d.asm.dynCall_iiiiiiii.apply(null,arguments)};d.dynCall_iiii=function(){return d.asm.dynCall_iiii.apply(null,arguments)};
d.dynCall_viiiii=function(){return d.asm.dynCall_viiiii.apply(null,arguments)};d.dynCall_viiiiiii=function(){return d.asm.dynCall_viiiiiii.apply(null,arguments)};d.dynCall_iiiiiid=function(){return d.asm.dynCall_iiiiiid.apply(null,arguments)};d.dynCall_vi=function(){return d.asm.dynCall_vi.apply(null,arguments)};d.dynCall_vii=function(){return d.asm.dynCall_vii.apply(null,arguments)};d.dynCall_iiiiiii=function(){return d.asm.dynCall_iiiiiii.apply(null,arguments)};
d.dynCall_iiiiid=function(){return d.asm.dynCall_iiiiid.apply(null,arguments)};d.dynCall_ii=function(){return d.asm.dynCall_ii.apply(null,arguments)};d.dynCall_viijii=function(){return d.asm.dynCall_viijii.apply(null,arguments)};d.dynCall_iiiiij=function(){return d.asm.dynCall_iiiiij.apply(null,arguments)};d.dynCall_viii=function(){return d.asm.dynCall_viii.apply(null,arguments)};d.dynCall_v=function(){return d.asm.dynCall_v.apply(null,arguments)};
d.dynCall_iiiiiiiii=function(){return d.asm.dynCall_iiiiiiiii.apply(null,arguments)};d.dynCall_iiiii=function(){return d.asm.dynCall_iiiii.apply(null,arguments)};d.dynCall_viiiiii=function(){return d.asm.dynCall_viiiiii.apply(null,arguments)};d.dynCall_iii=function(){return d.asm.dynCall_iii.apply(null,arguments)};d.dynCall_iiiiii=function(){return d.asm.dynCall_iiiiii.apply(null,arguments)};d.dynCall_viiii=function(){return d.asm.dynCall_viiii.apply(null,arguments)};v.G=d.stackAlloc;v.W=d.stackSave;
v.V=d.stackRestore;v.ia=d.establishStackSpace;v.g=d.setTempRet0;v.P=d.getTempRet0;d.asm=hc;
if(P)if("function"===typeof d.locateFile?P=d.locateFile(P):d.memoryInitializerPrefixURL&&(P=d.memoryInitializerPrefixURL+P),ca||da){var ic=d.readBinary(P);J.set(ic,v.o)}else{var kc=function(){d.readAsync(P,jc,function(){throw"could not load memory initializer "+P;})};Ra();var jc=function(a){a.byteLength&&(a=new Uint8Array(a));J.set(a,v.o);d.memoryInitializerRequest&&delete d.memoryInitializerRequest.response;Sa()};if(d.memoryInitializerRequest){var lc=function(){var a=d.memoryInitializerRequest;200!==
a.status&&0!==a.status?(console.warn("a problem seems to have happened with Module.memoryInitializerRequest, status: "+a.status+", retrying "+P),kc()):jc(a.response)};d.memoryInitializerRequest.response?setTimeout(lc,0):d.memoryInitializerRequest.addEventListener("load",lc)}else kc()}function ja(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ja.prototype=Error();ja.prototype.constructor=ja;
var mc=null,Qa=function nc(){d.calledRun||oc();d.calledRun||(Qa=nc)};d.callMain=d.ea=function(a){function b(){for(var a=0;3>a;a++)e.push(0)}a=a||[];La||(La=!0,Fa(Ha));var c=a.length+1,e=[G(Na(d.thisProgram),"i8",0)];b();for(var f=0;f<c-1;f+=1)e.push(G(Na(a[f]),"i8",0)),b();e.push(0);e=G(e,"i32",0);try{var h=d._main(c,e,0);pc(h,!0)}catch(g){g instanceof ja||("SimulateInfiniteLoop"==g?d.noExitRuntime=!0:((a=g)&&"object"===typeof g&&g.stack&&(a=[g,g.stack]),d.k("exception thrown: "+a),d.quit(1,g)))}finally{}};
function oc(a){function b(){if(!d.calledRun&&(d.calledRun=!0,!la)){La||(La=!0,Fa(Ha));Fa(Ia);if(d.onRuntimeInitialized)d.onRuntimeInitialized();d._main&&qc&&d.callMain(a);if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var b=d.postRun.shift();Ka.unshift(b)}Fa(Ka)}}a=a||d.arguments;null===mc&&(mc=Date.now());if(!(0<O)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)Ma();Fa(Ga);0<O||d.calledRun||(d.setStatus?(d.setStatus("Running..."),
setTimeout(function(){setTimeout(function(){d.setStatus("")},1);b()},1)):b())}}d.run=d.run=oc;function pc(a,b){if(!b||!d.noExitRuntime){if(!d.noExitRuntime&&(la=!0,u=void 0,Fa(Ja),d.onExit))d.onExit(a);ca&&process.exit(a);d.quit(a,new ja(a))}}d.exit=d.exit=pc;var rc=[];
function D(a){void 0!==a?(d.print(a),d.k(a),a=JSON.stringify(a)):a="";la=!0;var b="abort("+a+") at "+xa()+"\nIf this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.";rc&&rc.forEach(function(c){b=c(b,a)});throw b;}d.abort=d.abort=D;if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();var qc=!0;d.noInitialRun&&(qc=!1);oc();var sc=new Uint8Array(1024);window.re2validator={};
window.re2validator.validate=function(a){a=ua(a,sc,0,1024);return d._validate(sc.subarray(0,a))};window.re2validator.ready=new Promise(function(a){var b=setInterval(function(){d._validate&&(clearInterval(b),a())},1)});
